### ISSUE TITLE
Consider interpolation and validation across files

### ISSUE THREAD

**Issue by dhcole** [dhcole/csv-test#6]
via @harrisj 

> So, you’d have a namespaced variable in your interpolation like ‘expenses$net’ or such, if you can do this `csv-test validation.csv expenses=expenses.csv`

**Comment by harrisj** [comment]
Basically, the idea is that you might be able to do validations like this

``` yaml
income.net:
  type: integer
  formula: "{income.gross} - {expenses.gross}"
```

but probably with something a bit more elegant and a way the complies with JS and YAML naming rules. You could argue that enforcing validations across multiple CSV files would be best left to custom code that is run after each file is individually checked by csv-test. Also, perhaps complicated validations should be specified in a separate file of JS functions as was suggested in #7

**Comment by dhcole** [comment]
#10 sets up a way to write custom functions. I've included an example in the readme and tests for validating that a field is the sum of other fields.

I think this mostly addresses this issue. I'm not sure how to address comparing values across spreadsheets, since this application is set up to read files in streams. Reading as streams allows it to work quickly and efficiently on very large files, but it doesn't provide a way to compare across anything other than a given row.

This is also complicated by the need to have some sort of key to link rows across the spreadsheets.

If you wanted to store a whole file in memory for comparisons like this, you could do so with a custom validator. In your validator function, you would need to store the comparison data and use it for each test. Since this would be run on each test, it would more efficient to convert your data to JS or JSON and `require` it.

``` js
var expenses = require('path/to/file'); // pre-formatted JS / JSON data 
module.exports = {
  compareExpenses: function(value) {
    if (field === 'gross') return +value === (this.row.gross - expenses[this.row.foreignKey].gross);
    return true;
  }
};
```

@harrisj certainly not elegant, but would this work for your use case?

**Comment by harrisj** [comment]
It would work. It could also be argued that such extra constraints would probably be outside the scope of csv-test's abilities and the files should be assessed individually first by csv-test for basic errors and then validated by a custom script that would read in values from multiple sheets to check them out. This is not really in the scope of csv-test, because at that point we are more likely to be doing INNER JOINs and other things that SQL does well.

**Comment by dhcole** [comment]
Ok, then let's close for now unless some better solution emerges. #10 shipped, so you can `npm update -g csv-test` to use the version with custom functions and a more consistent validator format.
