### ISSUE TITLE
Handle blank columns as NULL values instead of empty strings

### ISSUE THREAD

**Issue by harrisj** [dhcole/csv-test#8]
I have a CSV with an column that can sometimes be nil. This is indicated in the CSV as an empty column (as opposed to a string like `null` or `nil`). It is triggering an issue with the validation for In `"in" validation rule failed for input: ''`. I suspect this will also be an issue for Integer and other columns. Can we have empty column values generically default to nil before they are validated, since that is what I have usually seen (as opposed to explicit nil values)

**Comment by dhcole** [comment]
#10 switches to a different library that treats [all input as strings](https://github.com/chriso/validator.js/blob/master/README.md#strings-only). Given this issue and how different CSV writers will format numbers in different ways — 3 vs "3" — this change will make the tests more consistent.

To test that a string is not empty, test with `isLength: 1`, which tests for whether the length of the value is greater or equal to 1.
